config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
   sessions:      'admins/sessions',
   passwords:     'admins/passwords',
   registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
   sessions:      'users/sessions',
   passwords:     'users/passwords',
   registrations: 'users/registrations'
  }

  root to:'top#top'

  namespace :admin do
    resources :users, only:[:index, :show, :edit, :updae, :destroy]
    resources :records, only:[:index, :show, :edit, :update, :destroy]
    resources :spots, only:[:index, :show, :edit, :update, :destroy]
  end
  scope module: :public do
    resources :users, only:[:show, :edit, :update, :destroy] do
          get "/user_records" => "records#user_records"
    end
    resources :records
    get '/spot_place' => "spots#spot_place"
    resources :spots, only:[:show]
  end

  resources :regions, only:[:show]

  resources :prefectures, only:[:show]

  namespace :admin do
    resources :places
  end
  scope module: :public do
    resources :places, only:[:show] do
      resource :went_prefectures, only:[:create, :destroy]
      patch "/show_count" => "places#show_count",as: 'show_count'
      resource :goes, only:[:create, :destroy, :show]
      get '/comment_index' => "comments#comment_index"
    	resources :comments, only:[:new, :show, :create, :destroy] do
    		resource :likes, only:[:create, :destroy]
      end
    end
    resources :comments, only:[:show]
  end

  get "/search_index/places" => "top#search_index"

  get "/search" => "top#search"

  get "/goes" => "public/goes#goes_list"

  get '/post/hashtag/:name' => "public/comments#hashtag"




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :place
	has_many :comments_hashtags
	has_many :likes
	has_many :comment_images, dependent: :destroy
	has_and_belongs_to_many :hashtags

	accepts_attachments_for :comment_images, attachment: :image

	validates_presence_of :title

	 after_create do
    comment = Comment.find_by(id: self.id)
    hashtags  = self.text.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      #ハッシュタグは先頭の'#'を外した上で保存
      tag = Hashtag.find_or_create_by(name: hashtag.downcase.delete('#'))
      comment.hashtags << tag
    end
  end

  before_update do
    comment = Comment.find_by(id: self.id)
    comment.hashtags.clear
    hashtags = self.text.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Hashtag.find_or_create_by(name: hashtag.downcase.delete('#'))
      comment.hashtags << tag
    end
  end
end

app/models/comment_image.rb
class CommentImage < ApplicationRecord
	belongs_to :comment
	attachment :image
end

app/models/go.rb
class Go < ApplicationRecord
	belongs_to :place
	belongs_to :user
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
	has_many :comments_hashtags
	has_and_belongs_to_many :comments

	validates :name, presence: true, length: {maximum:99}
	validates_uniqueness_of :name
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :comment
end

app/models/organization.rb
class Organization < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
	geocoded_by :place_name
    after_validation :geocode, if: :place_name_changed?

	attachment :place_image

	belongs_to :prefecture
	has_many :gos, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :went_prefectures, dependent: :destroy

	validates_uniqueness_of :place_name

	def self.search(search)
		if search
			Place.where(['place_name Like?', "%#{search}%"])
		else
			Place.all
		end
	end

	def favorited_by?(user)
          gos.where(user_id: user.id).exists?
    end

end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
	has_many :places
	belongs_to :region
end

app/models/record.rb
class Record < ApplicationRecord
	belongs_to :user
	has_many :spots, inverse_of: :record, dependent: :destroy
	accepts_nested_attributes_for :spots, reject_if: :all_blank, allow_destroy: true
end

app/models/region.rb
class Region < ApplicationRecord
	has_many :prefectures
end

app/models/season.rb
class Season < ApplicationRecord
end

app/models/spot.rb
class Spot < ApplicationRecord
	belongs_to :record
	attachment :spot_image

	validates_presence_of :prefecture_id
	validates_presence_of :spot_name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :gos
  has_many :comments, dependent: :destroy
  has_many :records, dependent: :destroy
  has_one :went, dependent: :destroy

  after_create:create_went

  validates :user_introduction, length: {maximum:150}
  validates :name, length: { minimum: 2, maximum: 20 }

 private
  def create_went
  	went = Went.new(user_id: self.id, prefecture_count:0)
    went.save
  end
end

app/models/went.rb
class Went < ApplicationRecord
	belongs_to :user
    has_many :went_prefectures, dependent: :destroy
end

app/controllers/top_controller.rb
class TopController < ApplicationController
	def top
		@favorites = Place.find(Go.group(:place_id).order('count(place_id) desc').limit(4).pluck(:place_id))
		@show_ranking = Place.all.order(show_count: "DESC").limit(3)
=begin
		a = Comment.arel_table
		b = CommentImage.arel_table
		condition = b[:comment_id].eq(a[:id])
		@comments = Comment.where(CommentImage.where(condition).exists).order(created_at: "DESC").limit(3)
=end
		@comments = []
		cnt = 0
		Comment.all.order(created_at: "DESC").each do |a|
			break if cnt == 3
				if a.comment_images.count != 0
					@comments << a
					cnt +=1
				end
		end

		@comment_images = []
		@comments.each do |comment|
			if comment.comment_images.present?
		 		image = CommentImage.where(comment_id: comment.id).first
		 		@comment_images << image
		 	end
	    end

	    @records = Record.all.order(created_at: "DESC").limit(3)
	    @spots = []
	    @records.each do |record|
	    	spot = Spot.where(record_id: record.id).first
	    	@spots << spot
	    end
	end

	def search
		@random_place = Place.where( 'id >= ?', rand(Place.first.id..Place.last.id) ).first
		@regions = Region.all
		@prefectures = Prefecture.all
		@comments = Comment.all
	end

	def search_index
		@places_search = Place.search(params[:search]).order(prefecture_id: "ASC")
	end
end

app/helpers/goes_helper.rb
module GoesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wents_helper.rb
module WentsHelper
end

app/views/top/search.html.erb
<div class="body">
    <div class="container">
        <div class="row search-random">
            <div class="col-xs-8">
                <div class="search-box">
                    <%= form_tag search_index_places_path, :method => 'get' do %>
                        <%= text_field_tag :search %>
                        <%= submit_tag "検索", :title => nil %>
                    <% end %>
                </div>
            </div>
            <div class="col-xs-4">
                <div class="css-fukidashi">
                    <%= link_to "どっかに行く", place_path(@random_place), class:"random" %>
                    <p class="fukidashi">観光地をランダムで一つ表示します</p>
                </div>
            </div>
        </div>

    <script type="text/javascript" src="javascripts/jquery.japan-map.min.js"></script>
    <script type="text/javascript">
        $(function(){
            var areaLinks = {
                1: '/prefectures/1',
                2: '/prefectures/2',
                3: '/prefectures/3',
                4: '/prefectures/4',
                5: '/prefectures/5',
                6: '/prefectures/6',
                7: '/prefectures/7',
                8: '/prefectures/12',
                9: '/prefectures/9',
                10: '/prefectures/10',
                11: '/prefectures/11',
                12: '/prefectures/13',
                13: '/prefectures/8',
                14: '/prefectures/14',
                15: '/prefectures/17',
                16: '/prefectures/18',
                17: '/prefectures/19',
                18: '/prefectures/20',
                19: '/prefectures/16',
                20: '/prefectures/15',
                21: '/prefectures/22',
                22: '/prefectures/21',
                23: '/prefectures/24',
                24: '/prefectures/23',
                25: '/prefectures/29',
                26: '/prefectures/25',
                27: '/prefectures/26',
                28: '/prefectures/27',
                29: '/prefectures/28',
                30: '/prefectures/30',
                31: '/prefectures/31',
                32: '/prefectures/32',
                33: '/prefectures/33',
                34: '/prefectures/34',
                35: '/prefectures/35',
                36: '/prefectures/38',
                37: '/prefectures/36',
                38: '/prefectures/37',
                39: '/prefectures/39',
                40: '/prefectures/40',
                41: '/prefectures/41',
                42: '/prefectures/42',
                43: '/prefectures/43',
                44: '/prefectures/44',
                45: '/prefectures/45',
                46: '/prefectures/46',
                47: '/prefectures/47',
        };
        var areas = [
            {code : 1, name: "北海道", color: "#7f7eda", hoverColor: "#b3b2ee", prefectures: [1]},
            {code : 2, name: "青森", color: "#759ef4", hoverColor: "#98b9ff", prefectures: [2]},
            {code : 3, name: "岩手", color: "#759ef4", hoverColor: "#98b9ff", prefectures: [3]},
            {code : 4, name: "宮城", color: "#759ef4", hoverColor: "#98b9ff", prefectures: [4]},
            {code : 5, name: "秋田", color: "#759ef4", hoverColor: "#98b9ff", prefectures: [5]},
            {code : 6, name: "山形", color: "#759ef4", hoverColor: "#98b9ff", prefectures: [6]},
            {code : 7, name: "福島", color: "#759ef4", hoverColor: "#98b9ff", prefectures: [7]},
            {code : 8, name: "茨城", color: "#7ecfea", hoverColor: "#b7e5f4", prefectures: [8]},
            {code : 9, name: "栃木", color: "#7ecfea", hoverColor: "#b7e5f4", prefectures: [9]},
            {code : 10, name: "群馬", color: "#7ecfea", hoverColor: "#b7e5f4", prefectures: [10]},
            {code : 11, name: "埼玉", color: "#7ecfea", hoverColor: "#b7e5f4", prefectures: [11]},
            {code : 12, name: "千葉", color: "#7ecfea", hoverColor: "#b7e5f4", prefectures: [12]},
            {code : 13, name: "東京", color: "#7ecfea", hoverColor: "#b7e5f4", prefectures: [13]},
            {code : 14, name: "神奈川", color: "#7ecfea", hoverColor: "#b7e5f4", prefectures: [14]},
            {code : 15, name: "新潟", color: "#7cdc92", hoverColor: "#aceebb", prefectures: [15]},
            {code : 16, name: "富山", color: "#7cdc92", hoverColor: "#aceebb", prefectures: [16]},
            {code : 17, name: "石川", color: "#7cdc92", hoverColor: "#aceebb", prefectures: [17]},
            {code : 18, name: "福井", color: "#7cdc92", hoverColor: "#aceebb", prefectures: [18]},
            {code : 19, name: "山梨", color: "#7cdc92", hoverColor: "#aceebb", prefectures: [19]},
            {code : 20, name: "長野", color: "#7cdc92", hoverColor: "#aceebb", prefectures: [20]},
            {code : 21, name: "岐阜", color: "#7cdc92", hoverColor: "#aceebb", prefectures: [21]},
            {code : 22, name: "静岡", color: "#7cdc92", hoverColor: "#aceebb", prefectures: [22]},
            {code : 23, name: "愛知", color: "#7cdc92", hoverColor: "#aceebb", prefectures: [23]},
            {code : 24, name: "三重", color: "#ffe966", hoverColor: "#fff19c", prefectures: [24]},
            {code : 25, name: "滋賀", color: "#ffe966", hoverColor: "#fff19c", prefectures: [25]},
            {code : 26, name: "京都", color: "#ffe966", hoverColor: "#fff19c", prefectures: [26]},
            {code : 27, name: "大阪", color: "#ffe966", hoverColor: "#fff19c", prefectures: [27]},
            {code : 28, name: "兵庫", color: "#ffe966", hoverColor: "#fff19c", prefectures: [28]},
            {code : 29, name: "奈良", color: "#ffe966", hoverColor: "#fff19c", prefectures: [29]},
            {code : 30, name: "和歌山", color: "#ffe966", hoverColor: "#fff19c", prefectures: [30]},
            {code : 31, name: "鳥取", color: "#ffcc66", hoverColor: "#ffe0a3", prefectures: [31]},
            {code : 32, name: "島根", color: "#ffcc66", hoverColor: "#ffe0a3", prefectures: [32]},
            {code : 33, name: "岡山", color: "#ffcc66", hoverColor: "#ffe0a3", prefectures: [33]},
            {code : 34, name: "広島", color: "#ffcc66", hoverColor: "#ffe0a3", prefectures: [34]},
            {code : 35, name: "山口", color: "#ffcc66", hoverColor: "#ffe0a3", prefectures: [35]},
            {code : 36, name: "徳島", color: "#fb9466", hoverColor: "#ffbb9c", prefectures: [36]},
            {code : 37, name: "香川", color: "#fb9466", hoverColor: "#ffbb9c", prefectures: [37]},
            {code : 38, name: "愛媛", color: "#fb9466", hoverColor: "#ffbb9c", prefectures: [38]},
            {code : 39, name: "高知", color: "#fb9466", hoverColor: "#ffbb9c", prefectures: [39]},
            {code : 40, name: "福岡", color: "#ff9999", hoverColor: "#ffbdbd", prefectures: [40]},
            {code : 41, name: "佐賀", color: "#ff9999", hoverColor: "#ffbdbd", prefectures: [41]},
            {code : 42, name: "長崎", color: "#ff9999", hoverColor: "#ffbdbd", prefectures: [42]},
            {code : 43, name: "熊本", color: "#ff9999", hoverColor: "#ffbdbd", prefectures: [43]},
            {code : 44, name: "大分", color: "#ff9999", hoverColor: "#ffbdbd", prefectures: [44]},
            {code : 45, name: "宮崎", color: "#ff9999", hoverColor: "#ffbdbd", prefectures: [45]},
            {code : 46, name: "鹿児島", color: "#ff9999", hoverColor: "#ffbdbd", prefectures: [46]},
            {code : 47, name: "沖縄", color: "#eb98ff", hoverColor: "#f5c9ff", prefectures: [47]},
        ];
        $("#map-container").japanMap({
            width: 730,
            selection: "area",
            areas: areas,
            backgroundColor : "#dcdcdc",
            borderLineColor: "#f2fcff",
            borderLineWidth : 0.25,
            lineColor : "#a0a0a0",
            lineWidth: 1,
            drawsBoxLine: true,
            showsPrefectureName: true,
            prefectureNameType: "short",
            movesIslands : true,
            fontSize : 11,
            fontShadowColor : "#fff",
            onSelect:function(data){
                location.href = areaLinks[data.area.code];
            }
         });
    });
    </script>

            <div id="map-container" class="map"></div>
                <div class="regions">
                    <% @regions.each do |region| %>
                        <%= link_to region_path(region) do %>
                            <h3><%= region.region_name %></h3>
                        <% end %>
                    <% end %>
                </div>
        </div>
    </div>
</div>

app/views/top/search_index.html.erb
<div class="body">
    <div class="container">
        <div class="row">
    	   <% if @places_search.count > 0 %>
    	       <h3>観光地検索一覧</h3>
    	       <div class="row">
    	           <% @places_search.each do |place| %>
                        <div class="col-xs-4">
                            <%= link_to place_show_count_path(place), method: :patch do %>
                                <%= place.place_name %>
                                    <p><%= attachment_image_tag place, :place_image, :fill, 300, 200, format: "jpg", fallback:"/images/no_image.jpg", size:'300x200' %></p>
                            <% end %>
                        </div>
    	           <% end %>
                </div>
            <% else %>
             <h2>検索に一致する場所がありませんでした。</h2>
    		<% end %>
        </div>
    </div>
</div>

app/views/top/top.html.erb
<div class="body">
	<div class="container">
		<div class="row">
			<script>
				$(document).ready(function(){
					$('.bxslider').bxSlider({
						auto: true,           // 自動スライド
						speed: 1000,          // スライドするスピード
						moveSlides: 1,        // 移動するスライド数
						pause: 3000,          // 自動スライドの待ち時間
						maxSlides: 2,         // 一度に表示させる最大数
						slideWidth: 400,      // 各スライドの幅
						randomStart: true,    // 最初に表示するスライドをランダムに設定
						autoHover: true       // ホバー時に自動スライドを停止
					});
				});
			</script>
			<h3>おすすめ</h3>
				<div class="row">
					<ul class="bxslider">
						<% @favorites.each do |favorite| %>
							<li><%= link_to place_show_count_path(favorite), method: :patch do %>
								<%= attachment_image_tag favorite, :place_image, :fill, 400, 350, format:"jpg" %>
								<h4><%= favorite.place_name %></h4>
								<% end %>
							</li>
						<% end %>
					</ul>
				</div>
			<h3>閲覧数</h3>
				<div class="row">
					<% @show_ranking.each do |show| %>
						<div class="col-xs-4">
							<div class="thumbnail">
								<%= link_to place_show_count_path(show), method: :patch do %>
									<div class="top-image">
										<%= attachment_image_tag show, :place_image, :fill, 400, 200, format:"jpg", fallback:"/images/no_image.jpg", class:"top-image" %>
									</div>
									<%= show.place_name %>
								<% end %>
							</div>
						</div>
					<% end %>
				</div>
			<h3>新着くちコミ</h3>
				<div class="row">
					<% @comment_images.each do|image| %>
						<div class="col-xs-4">
							<div class="thumbnail">
								<%= link_to comment_path(image.comment.id) do %>
									<div class="top-image">
										<%= attachment_image_tag image, :image, :fill, 400, 200, format:"jpg", fallback:"/images/no_image.jpg", fallback:"no_image.jpg", class:"top-image" %>
									</div>
									<%= image.comment.title %>
								<% end %>
							</div>
						</div>
					<% end %>
				</div>
			<h3>新しい旅の記録</h3>
				<div class="row">
					<% @spots.each do|spot| %>
						<div class="col-xs-4">
							<div class="thumbnail">
								<%= link_to record_path(spot.record.id) do %>
									<div class="top-image">
										<%= attachment_image_tag spot, :spot_image, :fill, 400, 200, format:"jpg", fallback:"/images/no_image.jpg", class:"top-image" %>
									</div>
									<%= spot.record.record_title %>
								<% end %>
							</div>
						</div>
					<% end %>
				</div>
		</div>
	</div>
</div>