config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
   sessions:      'admins/sessions',
   passwords:     'admins/passwords',
   registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
   sessions:      'users/sessions',
   passwords:     'users/passwords',
   registrations: 'users/registrations'
  }

  root to:'top#top'

  namespace :admin do
    resources :users, only:[:index, :show, :edit, :updae, :destroy]
    resources :records, only:[:index, :show, :edit, :update, :destroy]
    resources :spots, only:[:index, :show, :edit, :update, :destroy]
  end
  scope module: :public do
    resources :users, only:[:show, :edit, :update, :destroy] do
          get "/user_records" => "records#user_records"
    end
    resources :records
    get '/spot_place' => "spots#spot_place"
    resources :spots, only:[:show]
  end

  resources :regions, only:[:show]

  resources :prefectures, only:[:show]

  namespace :admin do
    resources :places
  end
  scope module: :public do
    resources :places, only:[:show] do
      resource :went_prefectures, only:[:create, :destroy]
      patch "/show_count" => "places#show_count",as: 'show_count'
      resource :goes, only:[:create, :destroy, :show]
      get '/comment_index' => "comments#comment_index"
    	resources :comments, only:[:new, :show, :create, :destroy] do
    		resource :likes, only:[:create, :destroy]
      end
    end
    resources :comments, only:[:show]
  end

  get "/search_index/places" => "top#search_index"

  get "/search" => "top#search"

  get "/goes" => "public/goes#goes_list"

  get '/post/hashtag/:name' => "public/comments#hashtag"




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :place
	has_many :comments_hashtags
	has_many :likes
	has_many :comment_images, dependent: :destroy
	has_and_belongs_to_many :hashtags

	accepts_attachments_for :comment_images, attachment: :image

	validates_presence_of :title

	 after_create do
    comment = Comment.find_by(id: self.id)
    hashtags  = self.text.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      #ハッシュタグは先頭の'#'を外した上で保存
      tag = Hashtag.find_or_create_by(name: hashtag.downcase.delete('#'))
      comment.hashtags << tag
    end
  end

  before_update do
    comment = Comment.find_by(id: self.id)
    comment.hashtags.clear
    hashtags = self.text.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Hashtag.find_or_create_by(name: hashtag.downcase.delete('#'))
      comment.hashtags << tag
    end
  end
end

app/models/comment_image.rb
class CommentImage < ApplicationRecord
	belongs_to :comment
	attachment :image
end

app/models/go.rb
class Go < ApplicationRecord
	belongs_to :place
	belongs_to :user
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
	has_many :comments_hashtags
	has_and_belongs_to_many :comments

	validates :name, presence: true, length: {maximum:99}
	validates_uniqueness_of :name
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :comment
end

app/models/organization.rb
class Organization < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
	geocoded_by :place_name
    after_validation :geocode, if: :place_name_changed?

	attachment :place_image

	belongs_to :prefecture
	has_many :gos, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :went_prefectures, dependent: :destroy

	validates_uniqueness_of :place_name

	def self.search(search)
		if search
			Place.where(['place_name Like?', "%#{search}%"])
		else
			Place.all
		end
	end

	def favorited_by?(user)
          gos.where(user_id: user.id).exists?
    end

end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
	has_many :places
	belongs_to :region
end

app/models/record.rb
class Record < ApplicationRecord
	belongs_to :user
	has_many :spots, inverse_of: :record, dependent: :destroy
	accepts_nested_attributes_for :spots, reject_if: :all_blank, allow_destroy: true
end

app/models/region.rb
class Region < ApplicationRecord
	has_many :prefectures
end

app/models/season.rb
class Season < ApplicationRecord
end

app/models/spot.rb
class Spot < ApplicationRecord
	belongs_to :record
	attachment :spot_image

	validates_presence_of :prefecture_id
	validates_presence_of :spot_name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :gos
  has_many :comments, dependent: :destroy
  has_many :records, dependent: :destroy
  has_one :went, dependent: :destroy

  after_create:create_went

  validates :user_introduction, length: {maximum:150}
  validates :name, length: { minimum: 2, maximum: 20 }

 private
  def create_went
  	went = Went.new(user_id: self.id, prefecture_count:0)
    went.save
  end
end

app/models/went.rb
class Went < ApplicationRecord
	belongs_to :user
    has_many :went_prefectures, dependent: :destroy
end

app/helpers/goes_helper.rb
module GoesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wents_helper.rb
module WentsHelper
end

app/views/admin/_links.html.erb
<%= link_to "登録", new_admin_place_path, class:"btn btn-danger" %>
<%= link_to "観光地一覧", admin_places_path, class:"btn btn-primary" %>
<%= link_to "旅の記録一覧", admin_records_path, class:"btn btn-info" %>
<%= link_to "ユーザー一覧", admin_users_path, class:"btn btn-success" %>
<%= link_to "spot一覧", admin_spots_path, class:"btn btn-warning" %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tours</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c" rel="stylesheet">
    <link href="https://fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="//maps.google.com/maps/api/js?key=AIzaSyDz1Q-hJnwP4eOXr6WqA5NIk4Serbyu3z0"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>

  </head>

  <body>
    <header>
      <nav class="navbar navbar-default" style="background-color: white;">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample" >
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <span class="navbar-brand"><%= link_to "Tours",root_path,  class:"header_logo" %></span>
          </div>
          <div class="collapse navbar-collapse" id="navbarEexample">
            <ul class="nav navbar-nav navbar-right">
              <% if admin_signed_in? %>
                <li>
                  <%=link_to "ログアウト",destroy_admin_session_path, class:"glyphicon glyphicon-log-out", method: :delete %>
                </li>
                <li>
                  <%= link_to "観光地一覧",admin_places_path %>
                </li>
              <% elsif user_signed_in? %>

                <li>
                  <%= link_to user_path(current_user) do %>
                  <div class="head">
                      <p class="glyphicon glyphicon-user aria-hidden=true"></p>
                  </div>
                  <p>マイページ</p>
                  <% end %>
                </li>
                <li>
                  <%= link_to goes_path do %>
                  <div class="head">
                    <p class="glyphicon glyphicon-star aria-hidden=true"></p>
                  </div>
                  <p>行きたい</p>
                  <% end %>
                </li>
                <li>
                  <%= link_to new_record_path do %>
                  <div class="head">
                    <p class="glyphicon glyphicon-plus"></p>
                  </div>
                  <p>新規投稿</p>
                  <% end %>
                </li>
                <li>
                  <%= link_to search_path do %>
                  <div class="head">
                     <p class="glyphicon glyphicon-search aria-hidden=true"></p>
                  </div>
                  <p>検索</p>
                  <% end %>
                </li>
                <li>
                  <%=link_to "　ログアウト", destroy_user_session_path, class:"glyphicon glyphicon-log-in", method: :delete %>
                </li>
                    <nav class="header_nav nav-list">
                      <ul class="nav navbar-nav navbar-right">
                        <li>
                          ようこそ<%= truncate(current_user.name, length: 10) %>さん
                        </li>
                      </ul>
                    </nav>
              <% else %>
                <li>
                  <%= link_to new_user_session_path do %>
                  <div class="head">
                     <p class="glyphicon glyphicon-user aria-hidden=true"></p>
                  </div>
                  <p>マイページ</p>
                  <% end %>
                </li>
                <li>
                  <%= link_to goes_path do %>
                  <div class="head">
                    <p class="glyphicon glyphicon-star aria-hidden=true"></p>
                  </div>
                  <p>行きたい</p>
                  <% end %>
                </li>
                <li>
                  <%= link_to new_record_path do %>
                  <div class="head">
                    <p class="glyphicon glyphicon-plus"></p>
                  </div>
                  <p>新規投稿</p>
                  <% end %>
                </li>
                <li>
                    <%= link_to search_path do %>
                    <div class="head">
                     <p class="glyphicon glyphicon-search aria-hidden=true"></p>
                    </div>
                    <p>検索</p>
                    <% end %>
                </li>
                <li>
                  <%= link_to"新規登録", new_user_registration_path %>
                </li>
                <li>
                  <%= link_to"ログイン", new_user_session_path %>
                </li>
              <% end %>
            </ul>
          </div>
          </nav>
        </div>
      </div>
    </header>
    <main>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <div class="container">
            <%= value %>
          </div>
        </div>
      <% end %>
      <%= yield %>
    </main>
    <footer>
    </footer>
  </body>
</html>