config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
   sessions:      'admins/sessions',
   passwords:     'admins/passwords',
   registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
   sessions:      'users/sessions',
   passwords:     'users/passwords',
   registrations: 'users/registrations'
  }

  root to:'top#top'

  namespace :admin do
    resources :users, only:[:index, :show, :edit, :updae, :destroy]
    resources :records, only:[:index, :show, :edit, :update, :destroy]
    resources :spots, only:[:index, :show, :edit, :update, :destroy]
  end
  scope module: :public do
    resources :users, only:[:show, :edit, :update, :destroy] do
          get "/user_records" => "records#user_records"
    end
    resources :records
    get '/spot_place' => "spots#spot_place"
    resources :spots, only:[:show]
  end

  resources :regions, only:[:show]

  resources :prefectures, only:[:show]

  namespace :admin do
    resources :places
  end
  scope module: :public do
    resources :places, only:[:show] do
      resource :went_prefectures, only:[:create, :destroy]
      patch "/show_count" => "places#show_count",as: 'show_count'
      resource :goes, only:[:create, :destroy, :show]
      get '/comment_index' => "comments#comment_index"
    	resources :comments, only:[:new, :show, :create, :destroy] do
    		resource :likes, only:[:create, :destroy]
      end
    end
    resources :comments, only:[:show]
  end

  get "/search_index/places" => "top#search_index"

  get "/search" => "top#search"

  get "/goes" => "public/goes#goes_list"

  get '/post/hashtag/:name' => "public/comments#hashtag"




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :gos
  has_many :comments, dependent: :destroy
  has_many :records, dependent: :destroy
  has_one :went, dependent: :destroy

  after_create:create_went

  validates :user_introduction, length: {maximum:150}
  validates :name, length: { minimum: 2, maximum: 20 }

 private
  def create_went
  	went = Went.new(user_id: self.id, prefecture_count:0)
    went.save
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :authenticate_admin!

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@went = Went.find_by(user_id: @user.id)
		@went_prefecture = WentPrefecture.where(went_id: @went.id)
		places = @went_prefecture.pluck(:place_id)
		@went_places = Place.where(id: places).order(prefecture_id: "ASC")
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		@user.update
		redirect_to admin_user_path(@user.id)
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to admin_user_path
	end

	private
	def user_params
		params.require(:user).permit(:name, :email, :user_introduction, :profile_image)
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="body">
	<div class="body" style="margin-left: 100px;">
		<%= render 'admin/links' %>
		<h2>編集</h2>
		 <%= form_for(@user) do |f| %>
			 <% if @user.errors.any? %>
			  <div id="error_explanation">
			    <h2><%= @user.errors.count %>件のエラーが発生しました。</h2>
			    <ul>
			      <% @user.errors.full_messages.each do |message| %>
			        <li><%= message %></li>
			      <% end %>
			    </ul>
			   </div>
			 <% end %>
			<div class="edit-user">
				<label>ニックネーム</label>
				<%= f.text_field :name, class:"name", placeholder:"名前" %>
			</div>

			<div class="edit-user">
				<label>アイコン</label>
				<%= f.attachment_field :profile_image, placeholder: "image", class:"user_image" %>
			</div>

			<div class="edit-user">
				<label>自己紹介</label>
				<%= f.text_area :user_introduction, class:"introduction" %>
			</div>

			<div class="action">
				<%= f.submit "更新" %>
			</div>
		<% end %>
	</div>
</div>

app/views/admin/users/index.html.erb
<div class="body">
<h2>User一覧</h2>
<%= render 'admin/links' %>
	<table class="table table-hover table-inverse">
		<thead>
			<tr>
				<th>id</th>
				<th>名前</th>
				<th>メールアドレス</th>
				<th colspan='2'></th>
			</tr>
		</thead>

	<% @users.each do |user| %>
		<tbody>
			<tr>
				<td><%= user.id %></td>
				<td><%= user.name %></td>
				<td><%= user.email %></td>
				<td><%= link_to "詳細", admin_user_path(user), class:"btn-sm btn-success" %>
					<%= link_to "削除", admin_user_path(user), method: :delete, data: {confirm: "退会させますか?" }, class:"btn-sm btn-danger" %>
				</td>
			</tr>
		</tbody>
	<% end %>
	</table>
</div>

app/views/admin/users/show.html.erb
<div class="body">
  <div class="container">
      <div class="row">
      <%= render 'admin/links' %>
        <div class ="user-info">
          <h2>ユーザー情報</h2>
          <div class="row">

            <div class="col-xs-4">
              <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: "jpg", fallback:"no_image.jpg", class:"user-image user-left" %>
              <div class="user-edit">
                  <%= link_to "編集", edit_admin_user_path(@user), class:"btn btn-default glyphicon glyphicon-wrench user-left" %>
              </div>
            </div>

            <div class="col-xs-8">
              <table class="table">
               <tbody>
                 <tr></tr>
                 <tr>
                    <th>ニックネーム</th>
                    <th><%= @user.name %></th>
                  </tr>
                  <tr>
                   <th>自己紹介</th>
                   <th><%= @user.user_introduction %></th>
                  </tr>
               </tbody>
              </table>
            </div>
          </div>

          <div class="row">
            <h3>訪れた都道府県の数　<%= @went.prefecture_count %>/47</h3>
            <h3>訪れた場所の数　<%= @went_places.count %>ヶ所</h3>
            <h3><%= link_to"旅の記録", user_user_records_path(@user), class:"glyphicon glyphicon-send" %></h3>

            <% @went_places.each do |place| %>
            <div class="col-xs-4">
              <div class="thumbnail">
                <%= link_to place_path(place) do %>
                  <%= attachment_image_tag place, :place_image, :fill, 400, 200 %>
                <% end %>
                <%= place.place_name %>
              </div>
            </div>
            <% end %>

        </div>
      </div>
    </div>
  </div>
</div>