config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
   sessions:      'admins/sessions',
   passwords:     'admins/passwords',
   registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
   sessions:      'users/sessions',
   passwords:     'users/passwords',
   registrations: 'users/registrations'
  }

  root to:'top#top'

  namespace :admin do
    resources :users, only:[:index, :show, :edit, :updae, :destroy]
    resources :records, only:[:index, :show, :edit, :update, :destroy]
    resources :spots, only:[:index, :show, :edit, :update, :destroy]
  end
  scope module: :public do
    resources :users, only:[:show, :edit, :update, :destroy] do
          get "/user_records" => "records#user_records"
    end
    resources :records
    get '/spot_place' => "spots#spot_place"
    resources :spots, only:[:show]
  end

  resources :regions, only:[:show]

  resources :prefectures, only:[:show]

  namespace :admin do
    resources :places
  end
  scope module: :public do
    resources :places, only:[:show] do
      resource :went_prefectures, only:[:create, :destroy]
      patch "/show_count" => "places#show_count",as: 'show_count'
      resource :goes, only:[:create, :destroy, :show]
      get '/comment_index' => "comments#comment_index"
    	resources :comments, only:[:new, :show, :create, :destroy] do
    		resource :likes, only:[:create, :destroy]
      end
    end
    resources :comments, only:[:show]
  end

  get "/search_index/places" => "top#search_index"

  get "/search" => "top#search"

  get "/goes" => "public/goes#goes_list"

  get '/post/hashtag/:name' => "public/comments#hashtag"




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :place
	has_many :comments_hashtags
	has_many :likes
	has_many :comment_images, dependent: :destroy
	has_and_belongs_to_many :hashtags

	accepts_attachments_for :comment_images, attachment: :image

	validates_presence_of :title

	 after_create do
    comment = Comment.find_by(id: self.id)
    hashtags  = self.text.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      #ハッシュタグは先頭の'#'を外した上で保存
      tag = Hashtag.find_or_create_by(name: hashtag.downcase.delete('#'))
      comment.hashtags << tag
    end
  end

  before_update do
    comment = Comment.find_by(id: self.id)
    comment.hashtags.clear
    hashtags = self.text.scan(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Hashtag.find_or_create_by(name: hashtag.downcase.delete('#'))
      comment.hashtags << tag
    end
  end
end

app/models/comment_image.rb
class CommentImage < ApplicationRecord
	belongs_to :comment
	attachment :image
end

app/models/go.rb
class Go < ApplicationRecord
	belongs_to :place
	belongs_to :user
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
	has_many :comments_hashtags
	has_and_belongs_to_many :comments

	validates :name, presence: true, length: {maximum:99}
	validates_uniqueness_of :name
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :comment
end

app/models/organization.rb
class Organization < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
	geocoded_by :place_name
    after_validation :geocode, if: :place_name_changed?

	attachment :place_image

	belongs_to :prefecture
	has_many :gos, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :went_prefectures, dependent: :destroy

	validates_uniqueness_of :place_name

	def self.search(search)
		if search
			Place.where(['place_name Like?', "%#{search}%"])
		else
			Place.all
		end
	end

	def favorited_by?(user)
          gos.where(user_id: user.id).exists?
    end

end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
	has_many :places
	belongs_to :region
end

app/models/record.rb
class Record < ApplicationRecord
	belongs_to :user
	has_many :spots, inverse_of: :record, dependent: :destroy
	accepts_nested_attributes_for :spots, reject_if: :all_blank, allow_destroy: true
end

app/models/region.rb
class Region < ApplicationRecord
	has_many :prefectures
end

app/models/season.rb
class Season < ApplicationRecord
end

app/models/spot.rb
class Spot < ApplicationRecord
	belongs_to :record
	attachment :spot_image

	validates_presence_of :prefecture_id
	validates_presence_of :spot_name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :gos
  has_many :comments, dependent: :destroy
  has_many :records, dependent: :destroy
  has_one :went, dependent: :destroy

  after_create:create_went

  validates :user_introduction, length: {maximum:150}
  validates :name, length: { minimum: 2, maximum: 20 }

 private
  def create_went
  	went = Went.new(user_id: self.id, prefecture_count:0)
    went.save
  end
end

app/models/went.rb
class Went < ApplicationRecord
	belongs_to :user
    has_many :went_prefectures, dependent: :destroy
end

app/controllers/admin/records_controller.rb
class Admin::RecordsController < ApplicationController
	before_action :authenticate_admin!

	def index
		@records = Record.all
	end

	def show
		@record = Record.find(params[:id])
	end

	def destroy
		@record = Record.find(params[:id])
		@record.destroy
		redirect_to admin_records_path
	end
end

app/helpers/goes_helper.rb
module GoesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wents_helper.rb
module WentsHelper
end

app/views/admin/records/index.html.erb
<div class="body">
<h2>旅の記録一覧</h2>
<%= render 'admin/links' %>
	<table class="table table-hover table-inverse">
		<thead>
			<tr>
				<th>id</th>
				<th>ユーザー名</th>
				<th>タイトル</th>
				<th colspan='2'></th>
			</tr>
		</thead>

	<% @records.each do |record| %>
		<tbody>
			<tr>
				<td><%= record.id %></td>
				<td><%= record.user.name %></td>
				<td><%= record.record_title %></td>
				<td><%= link_to "詳細", admin_record_path(record), class:"btn-sm btn-success" %>
					<%= link_to "削除", admin_record_path(record), method: :delete, data: {confirm: "退会させますか?" }, class:"btn-sm btn-danger" %>
				</td>
			</tr>
		</tbody>
	<% end %>
	</table>
</div>

app/views/admin/records/show.html.erb
<div class="body">
	<div class="container">
		<div class="row">
			<%= render 'admin/links' %>
			<div class="col-md-8 col-md-offset-2">
				<h3><%= link_to admin_user_path(@record.user.id) do %>
						<%= @record.user.name %>
    				<% end %>
    				さんの旅の記録
				</h3>
				<strong>タイトル</strong>
				<div class="resord-title-show">
					<%= @record.record_title %>
				</div>
				<strong>感想</strong>
				<div class="record-text-show">
					<%= @record.record_text %>
				</div>

					<% @record.spots.each do |spot| %>
					<div class="record-spots">
					    <p>
							<strong>場所:</strong>
							<%= link_to spot_path(spot), class:"spot-name" do %>
								<%= spot.spot_name %>
							<% end %>
						</p>
						<p>
					    	<strong>日付:</strong>
					    	<%= spot.spot_date %>
					    </p>
						<p>
							<strong>一言感想:</strong>
							<div class="spot-title-show">
								<%= spot.spot_title %>
							</div>
						</p>
						<strong>お気に入りの一枚</strong>
						<div class="spot-image">
							<%= attachment_image_tag spot, :spot_image, :fill, 500, 300, format:"jpg", fallback:"/images/no_image.jpg", size:"500*300" %>
						</div>
					</div>
					<% end %>
			</div>
		</div>
	</div>
</div>